FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["UnitMicroService/UnitMicroService.csproj", "UnitMicroService/"]
RUN dotnet restore "UnitMicroService/UnitMicroService.csproj"
COPY . .
WORKDIR "/src/UnitMicroService"
RUN dotnet build "UnitMicroService.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "UnitMicroService.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "UnitMicroService.dll"]